services:
    - name: whatsapp-go
      type: web
      env: docker
      plan: free # Change to "starter" or higher for non-free plans
      dockerfilePath: ./docker/golang.Dockerfile
      buildCommand: "" # Optional, Render handles it for Docker
      startCommand: "" # Optional, handled by Dockerfile's CMD
      healthCheckPath: "/" # Optional, set the health check endpoint
      autoDeploy: true
      envVars:
        - key: PORT
          value: "3000"
      docker:
        image: aldinokemal2104/go-whatsapp-web-multidevice:latest
      ports:
        - port: 3000
  